<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Referentiel\Entities\Localite;

class LocaliteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Données extraites de la base de données de production
     * Codes postaux officiels conformes au Chapitre 3, Article 11
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::statement('TRUNCATE tr_localite');

        $data = [
            ['code_localite'=>'LOC_0001', 'lib_localite'=>'BRAZZAVILLE', 'code_officel'=>'BZ', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0002', 'lib_localite'=>'POINTE-NOIRE', 'code_officel'=>'PN', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0003', 'lib_localite'=>'LIKOUALA', 'code_officel'=>'LK', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0004', 'lib_localite'=>'SANGHA', 'code_officel'=>'SA', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0005', 'lib_localite'=>'CUVETTE-OUEST', 'code_officel'=>'CO', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0006', 'lib_localite'=>'CUVETTE', 'code_officel'=>'CV', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0007', 'lib_localite'=>'PLATEAUX', 'code_officel'=>'PL', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0008', 'lib_localite'=>'POOL', 'code_officel'=>'PO', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0009', 'lib_localite'=>'LEKOUMOU', 'code_officel'=>'LE', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0010', 'lib_localite'=>'BOUENZA', 'code_officel'=>'BO', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0011', 'lib_localite'=>'NIARI', 'code_officel'=>'NI', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0012', 'lib_localite'=>'KOUILOU', 'code_officel'=>'KL', 'code_type_localite'=>'TPLOC_0001', 'pompes_funebres'=>0, 'code_localite_parent'=>NULL, 'supprimer'=>0],
            ['code_localite'=>'LOC_0013', 'lib_localite'=>'DOLISIE', 'code_officel'=>'DOL', 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0011', 'supprimer'=>0],
            ['code_localite'=>'LOC_0014', 'lib_localite'=>'MOSSENDJO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0011', 'supprimer'=>0],
            ['code_localite'=>'LOC_0015', 'lib_localite'=>'SIBITI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0009', 'supprimer'=>0],
            ['code_localite'=>'LOC_0016', 'lib_localite'=>'POINTE-NOIRE', 'code_officel'=>'PN', 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0002', 'supprimer'=>0],
            ['code_localite'=>'LOC_0017', 'lib_localite'=>'DJAMBALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0018', 'lib_localite'=>'KINKALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0019', 'lib_localite'=>'KINTELE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0020', 'lib_localite'=>'IMPFONDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0021', 'lib_localite'=>'OWANDO', 'code_officel'=>'OW', 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0022', 'lib_localite'=>'OYO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0023', 'lib_localite'=>'EWO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0024', 'lib_localite'=>'OUESSO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0025', 'lib_localite'=>'LOANGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0012', 'supprimer'=>0],
            ['code_localite'=>'LOC_0026', 'lib_localite'=>'BRAZZAVILLE', 'code_officel'=>'BV', 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>1, 'code_localite_parent'=>'LOC_0001', 'supprimer'=>0],
            ['code_localite'=>'LOC_0027', 'lib_localite'=>'MADINGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0010', 'supprimer'=>0],
            ['code_localite'=>'LOC_0028', 'lib_localite'=>'NKAYI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0010', 'supprimer'=>0],
            ['code_localite'=>'LOC_0029', 'lib_localite'=>'POKOLA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0003', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0030', 'lib_localite'=>'FOUNDOU-FOUNDOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0013', 'supprimer'=>0],
            ['code_localite'=>'LOC_0031', 'lib_localite'=>'YOULOU-POUNGUI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0013', 'supprimer'=>0],
            ['code_localite'=>'LOC_0032', 'lib_localite'=>'DOLISIE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0013', 'supprimer'=>0],
            ['code_localite'=>'LOC_0033', 'lib_localite'=>'BOUALI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0014', 'supprimer'=>0],
            ['code_localite'=>'LOC_0034', 'lib_localite'=>'ITSIBOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0014', 'supprimer'=>0],
            ['code_localite'=>'LOC_0035', 'lib_localite'=>'SIBITI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0036', 'lib_localite'=>'LUMUMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0016', 'supprimer'=>0],
            ['code_localite'=>'LOC_0037', 'lib_localite'=>'MVOUMVOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0016', 'supprimer'=>0],
            ['code_localite'=>'LOC_0038', 'lib_localite'=>'TIE-TIE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0016', 'supprimer'=>0],
            ['code_localite'=>'LOC_0039', 'lib_localite'=>'LOANDJILI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0016', 'supprimer'=>0],
            ['code_localite'=>'LOC_0040', 'lib_localite'=>'MONGO-POUKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0016', 'supprimer'=>0],
            ['code_localite'=>'LOC_0041', 'lib_localite'=>'NGOYO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0016', 'supprimer'=>0],
            ['code_localite'=>'LOC_0042', 'lib_localite'=>'DJAMBALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0043', 'lib_localite'=>'KINKALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0044', 'lib_localite'=>'KINTELE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0045', 'lib_localite'=>'IMPFONDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0046', 'lib_localite'=>'OWANDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0047', 'lib_localite'=>'OYO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0022', 'supprimer'=>0],
            ['code_localite'=>'LOC_0048', 'lib_localite'=>'EWO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0049', 'lib_localite'=>'NZALANGOYE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0024', 'supprimer'=>0],
            ['code_localite'=>'LOC_0050', 'lib_localite'=>'MBINDJO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0024', 'supprimer'=>0],
            ['code_localite'=>'LOC_0051', 'lib_localite'=>'LOANGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0025', 'supprimer'=>0],
            ['code_localite'=>'LOC_0052', 'lib_localite'=>'MAKELEKELE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0053', 'lib_localite'=>'BACONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0054', 'lib_localite'=>'POTO-POTO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0055', 'lib_localite'=>'MOUNGALI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0056', 'lib_localite'=>'OUENZE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0057', 'lib_localite'=>'TALANGAI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0058', 'lib_localite'=>'MFILOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0059', 'lib_localite'=>'MADIBOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0060', 'lib_localite'=>'DJIRI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0026', 'supprimer'=>0],
            ['code_localite'=>'LOC_0061', 'lib_localite'=>'MADINGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0062', 'lib_localite'=>'MWANA-NTO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0028', 'supprimer'=>0],
            ['code_localite'=>'LOC_0063', 'lib_localite'=>'SOULOUKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0028', 'supprimer'=>0],
            ['code_localite'=>'LOC_0064', 'lib_localite'=>'POKOLA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0004', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0029', 'supprimer'=>0],
            ['code_localite'=>'LOC_0065', 'lib_localite'=>'C.Q 101 CONGO-AFRICAIN', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0066', 'lib_localite'=>'C.Q 102 CAPABLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0067', 'lib_localite'=>'C.Q 103 AEROPORT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0068', 'lib_localite'=>'C.Q 104 BALOUMBOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0069', 'lib_localite'=>'C.Q 105 GRAND MARCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0070', 'lib_localite'=>'C.Q 106 DES EGLISES', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0071', 'lib_localite'=>'C.Q 107 BACONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0072', 'lib_localite'=>'C.Q 108 HERVÉ DELLOT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0073', 'lib_localite'=>'C.Q 109 BAKOUGNI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0074', 'lib_localite'=>'C.Q 110 MBOUKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0075', 'lib_localite'=>'C.Q 111 DIMEBEKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0076', 'lib_localite'=>'C.Q 112 PINARE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0077', 'lib_localite'=>'C.Q 113 TAHITI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0078', 'lib_localite'=>'C.Q.114 MPASSI-NGOLO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0079', 'lib_localite'=>'C.Q.115 MANGANDZI 1', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0030', 'supprimer'=>0],
            ['code_localite'=>'LOC_0080', 'lib_localite'=>'C.Q 201 MOUPEPE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0081', 'lib_localite'=>'C.Q 202 GAÏA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0082', 'lib_localite'=>'C.Q 203 LAC GAÏA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0083', 'lib_localite'=>'C.Q 204 CENTRE VILLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0084', 'lib_localite'=>'C.Q 205 PETIT ZANAGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0085', 'lib_localite'=>'C.Q 206 TSILA 1', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0086', 'lib_localite'=>'C.Q 207 TSILA 2', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0087', 'lib_localite'=>'C.Q 208 LISSANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0088', 'lib_localite'=>'C.Q 209 TELEVISION', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0089', 'lib_localite'=>'C.Q 201 MANGANDZI 2', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0090', 'lib_localite'=>'C.Q 211 PADI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0091', 'lib_localite'=>'C.Q 212 MONT FLEURY', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0092', 'lib_localite'=>'C.Q 213 UNITE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0031', 'supprimer'=>0],
            ['code_localite'=>'LOC_0093', 'lib_localite'=>'MBAMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0033', 'supprimer'=>0],
            ['code_localite'=>'LOC_0094', 'lib_localite'=>'PLANCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0033', 'supprimer'=>0],
            ['code_localite'=>'LOC_0095', 'lib_localite'=>'MAKENGUE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0033', 'supprimer'=>0],
            ['code_localite'=>'LOC_0096', 'lib_localite'=>'ITOMBE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0033', 'supprimer'=>0],
            ['code_localite'=>'LOC_0097', 'lib_localite'=>'MOUKAMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0033', 'supprimer'=>0],
            ['code_localite'=>'LOC_0098', 'lib_localite'=>'MOZARD', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0034', 'supprimer'=>0],
            ['code_localite'=>'LOC_0099', 'lib_localite'=>'YOMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0034', 'supprimer'=>0],
            ['code_localite'=>'LOC_0100', 'lib_localite'=>'MALEMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0034', 'supprimer'=>0],
            ['code_localite'=>'LOC_0101', 'lib_localite'=>'LIMBAMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0034', 'supprimer'=>0],
            ['code_localite'=>'LOC_0102', 'lib_localite'=>'NYANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0034', 'supprimer'=>0],
            ['code_localite'=>'LOC_0103', 'lib_localite'=>'LOUMINGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0104', 'lib_localite'=>'MATIBI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0105', 'lib_localite'=>'MAPINDI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0106', 'lib_localite'=>'MVOUBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0107', 'lib_localite'=>'MOUSSANDA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0108', 'lib_localite'=>'INDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0109', 'lib_localite'=>'MALIMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0110', 'lib_localite'=>'MOUSSIEHOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0111', 'lib_localite'=>'MIKAMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0112', 'lib_localite'=>'LOSSO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0113', 'lib_localite'=>'MOUKANDA ', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0114', 'lib_localite'=>'MONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0035', 'supprimer'=>0],
            ['code_localite'=>'LOC_0115', 'lib_localite'=>'CENTRE-VILLE (GARE CENTRALE)', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0116', 'lib_localite'=>'CENTRE- VILLE STADE F.A', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0117', 'lib_localite'=>'KM4 ATELIERS C.F.C.O', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0118', 'lib_localite'=>'KM4 CEG 5 FEVRIER', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0119', 'lib_localite'=>'EGLISE SAINT PIERRE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0120', 'lib_localite'=>'BASE AERIENNE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0121', 'lib_localite'=>'S.I.C TCHICHELLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0122', 'lib_localite'=>'MARCHE CENTRAL', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0123', 'lib_localite'=>'GRAND MOSQUEE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0124', 'lib_localite'=>'AUBERGE DE LA JUSTICE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0125', 'lib_localite'=>'JOIE DU CONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0126', 'lib_localite'=>'CEG O.C.H KWAME NKRUMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0127', 'lib_localite'=>'O.C.H STATION X-OIL', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0128', 'lib_localite'=>'O.C.H BAGUETTE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0129', 'lib_localite'=>'MBEMBA COUTE CHER', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0130', 'lib_localite'=>'M’ PITA MAISON D’ARRET', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0131', 'lib_localite'=>'M’PITA USINE PLASCO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0132', 'lib_localite'=>'TCHIMBAMBA AVIATION', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0133', 'lib_localite'=>'TCHIMBAMBA MARCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0036', 'supprimer'=>0],
            ['code_localite'=>'LOC_0134', 'lib_localite'=>'PLAGE,BASE AGIP', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0135', 'lib_localite'=>'EGLISE SAINT CHRISTOPHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0136', 'lib_localite'=>'MARCHE MVOUMVOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0137', 'lib_localite'=>'MARCHE MVOUMVOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0138', 'lib_localite'=>'KIF- KIF', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0139', 'lib_localite'=>'HOTEL DE LA PONTENEGRINE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0140', 'lib_localite'=>'EGLISE SAINTE BERNADETTE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0141', 'lib_localite'=>'CINEMA ROY', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0142', 'lib_localite'=>'CINEMA REX', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0143', 'lib_localite'=>'EGLISE KIMBAGUISTE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0144', 'lib_localite'=>'ECOLE NDENDE NIENGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0037', 'supprimer'=>0],
            ['code_localite'=>'LOC_0146', 'lib_localite'=>'EGLISE SAINT FRANCOIS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0147', 'lib_localite'=>'MARCHE TIE-TIE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0148', 'lib_localite'=>'DUO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0149', 'lib_localite'=>'MOULEMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0150', 'lib_localite'=>'NDAKA SOUSSOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0151', 'lib_localite'=>'MARCHE LIBERTE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0152', 'lib_localite'=>'MBOUKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0153', 'lib_localite'=>'MVOUNGOU 1 MARCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0154', 'lib_localite'=>'MVOUNGOU 2TERMINUS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0155', 'lib_localite'=>'MVOUNGOU 3 ECOLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0156', 'lib_localite'=>'MVOUNGOU 4 LA DIANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0157', 'lib_localite'=>'LOUSSALA 1 MARCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0158', 'lib_localite'=>'LOUSSALA 2 ECOLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0159', 'lib_localite'=>'CSI DU 15 OCTOBRE 1997 MPAKA 1 KM 8', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0160', 'lib_localite'=>'MPAKA 2 MATERNITE MOUISSOU MADELEINE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0161', 'lib_localite'=>'MPAKA 3 EGLISE SAINT-ESPRIT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0038', 'supprimer'=>0],
            ['code_localite'=>'LOC_0162', 'lib_localite'=>'LOANDILI 1 ECOLE BALOU CONSTANT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0163', 'lib_localite'=>'LOANDJILI 2 CEG MOE POATY', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0164', 'lib_localite'=>'NKOUIKOU MARCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0165', 'lib_localite'=>'TCHINIAMBI ECOLE B.M MAVOUNGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0166', 'lib_localite'=>'TCHINIAMBI 2 ECOLE 15 AOUT1963', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0167', 'lib_localite'=>'MONGO-KAMBA MARCHE DU PEUPLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0168', 'lib_localite'=>'MONGO KAMBA MOVIS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0169', 'lib_localite'=>'TCHIBATI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0170', 'lib_localite'=>'TCHINIAMBI MBOTA 1 ECOLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0171', 'lib_localite'=>'TCHINIAMBI MBOTA 2 CARLOS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0172', 'lib_localite'=>'MARCHE 1 MBOTA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0173', 'lib_localite'=>'MBOTA 2 ECOLE 8 FEVRIER1964', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0174', 'lib_localite'=>'BISSONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0039', 'supprimer'=>0],
            ['code_localite'=>'LOC_0175', 'lib_localite'=>'MONGO- MPOUKOU ECOLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0176', 'lib_localite'=>'SIAFOUMOU CSI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0177', 'lib_localite'=>'MBOTA RAFFINERIE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0178', 'lib_localite'=>'MBOTA RAFFINERIE OCEAN', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0179', 'lib_localite'=>'SONGOLO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0180', 'lib_localite'=>'FAUBOURG', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0181', 'lib_localite'=>'LOANDILI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0182', 'lib_localite'=>'TCHIALI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0183', 'lib_localite'=>'MAKAYABOU ZEPHIRIN', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0184', 'lib_localite'=>'TANDOU- SOUKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0185', 'lib_localite'=>'ECOLE NKOUNGA MAKOSSO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0186', 'lib_localite'=>'TCHICAYA ELOI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0187', 'lib_localite'=>'NKOUIKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0188', 'lib_localite'=>'NKOUIKOU TRABEC', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0040', 'supprimer'=>0],
            ['code_localite'=>'LOC_0189', 'lib_localite'=>'NGOYO 1 ECOLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0190', 'lib_localite'=>'NGOYO 2 C.M.A', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0191', 'lib_localite'=>'TCHIMBABOUKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0192', 'lib_localite'=>'TCHIMANI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0193', 'lib_localite'=>'COTE MATEVE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0194', 'lib_localite'=>'NANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0195', 'lib_localite'=>'MPAKA 120', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0196', 'lib_localite'=>'MPAKA 2 MARCHE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0197', 'lib_localite'=>'MPAKA 3 5 CHEMINS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0198', 'lib_localite'=>'DJENO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0041', 'supprimer'=>0],
            ['code_localite'=>'LOC_0199', 'lib_localite'=>'MONGOKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0049', 'supprimer'=>0],
            ['code_localite'=>'LOC_0200', 'lib_localite'=>'FAISCEAUX', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0049', 'supprimer'=>0],
            ['code_localite'=>'LOC_0201', 'lib_localite'=>'MINDONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0049', 'supprimer'=>0],
            ['code_localite'=>'LOC_0202', 'lib_localite'=>'POTO-POTO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0049', 'supprimer'=>0],
            ['code_localite'=>'LOC_0203', 'lib_localite'=>'CHATEAU D’EAU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0049', 'supprimer'=>0],
            ['code_localite'=>'LOC_0204', 'lib_localite'=>'MOMETA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0049', 'supprimer'=>0],
            ['code_localite'=>'LOC_0205', 'lib_localite'=>'CENTRE SPORTIF', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0206', 'lib_localite'=>'DIATA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0207', 'lib_localite'=>'KINGOUARI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0208', 'lib_localite'=>'KINSOUNDI(BARRAGE)', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0209', 'lib_localite'=>'MAMBA ( BIFOUITI)', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0210', 'lib_localite'=>'MAYOMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0211', 'lib_localite'=>'METEO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0212', 'lib_localite'=>'MOUNKOUNZI-NGONAKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0213', 'lib_localite'=>'NGANGOUONI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0214', 'lib_localite'=>'NIANIA (SITA DIA TSOLO)', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0215', 'lib_localite'=>'NGASSA (MATOUR)', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0052', 'supprimer'=>0],
            ['code_localite'=>'LOC_0216', 'lib_localite'=>'DAHOMEY', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0217', 'lib_localite'=>'GLACIERE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0218', 'lib_localite'=>'MBAMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0219', 'lib_localite'=>'MPISSA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0220', 'lib_localite'=>'NKEOUA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0221', 'lib_localite'=>'NIMBI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0222', 'lib_localite'=>'RIO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0223', 'lib_localite'=>'SAINT – PIERRE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0224', 'lib_localite'=>'TAHITI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0053', 'supprimer'=>0],
            ['code_localite'=>'LOC_0225', 'lib_localite'=>'AVENUE DE FRANCE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0054', 'supprimer'=>0],
            ['code_localite'=>'LOC_0226', 'lib_localite'=>'AVENUE DE DE PARIS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0054', 'supprimer'=>0],
            ['code_localite'=>'LOC_0227', 'lib_localite'=>'CAMPS 15 AOUT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0054', 'supprimer'=>0],
            ['code_localite'=>'LOC_0228', 'lib_localite'=>'OCH MOUNGALI 3', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0054', 'supprimer'=>0],
            ['code_localite'=>'LOC_0229', 'lib_localite'=>'5 FEVRIER', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0054', 'supprimer'=>0],
            ['code_localite'=>'LOC_0230', 'lib_localite'=>'ANCIENS COMBATTANTS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0231', 'lib_localite'=>'CEG DE LA PAIX', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0232', 'lib_localite'=>'CEG MATSOUA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0233', 'lib_localite'=>'DIX MAISONS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0234', 'lib_localite'=>'ECOLE DES BEAUX-ARTS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0235', 'lib_localite'=>'LA POUDRIERE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0236', 'lib_localite'=>'MARCHE DE 10 FRANCS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0237', 'lib_localite'=>'MOUKONDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0238', 'lib_localite'=>'PLAITEAU DES 15 ANS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0055', 'supprimer'=>0],
            ['code_localite'=>'LOC_0239', 'lib_localite'=>'BONEMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0240', 'lib_localite'=>'KIMBANGOU – MIKALOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0241', 'lib_localite'=>'MARCHE DE OUENZE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0242', 'lib_localite'=>'MASSAMBA RAPHAEL', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0243', 'lib_localite'=>'MOULEKE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0244', 'lib_localite'=>'MOUKONDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0245', 'lib_localite'=>'MPILA CENT FILS', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0246', 'lib_localite'=>'MPIERE – MPIERE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0247', 'lib_localite'=>'OUENZE MANDZADZA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0248', 'lib_localite'=>'PEYRE PIERRE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0056', 'supprimer'=>0],
            ['code_localite'=>'LOC_0249', 'lib_localite'=>'CHAMP DE TIR', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0250', 'lib_localite'=>'FLEUVE CONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0251', 'lib_localite'=>'GASTON LENDA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0252', 'lib_localite'=>'INTENDANCE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0253', 'lib_localite'=>'JOSEPH NGOLALI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0254', 'lib_localite'=>'MAMAN MBOUALE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0255', 'lib_localite'=>'MPILA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0256', 'lib_localite'=>'TEXACO TSIEME', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0057', 'supprimer'=>0],
            ['code_localite'=>'LOC_0257', 'lib_localite'=>'CASE BARNIER', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0258', 'lib_localite'=>'CITE DES 17', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0259', 'lib_localite'=>'INDZOULI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0260', 'lib_localite'=>'ITSALI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0261', 'lib_localite'=>'KAHOUNGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0262', 'lib_localite'=>'KIBOUENDE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0263', 'lib_localite'=>'KIELE THENARD', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0264', 'lib_localite'=>'MASSINA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0265', 'lib_localite'=>'MOUTABALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0266', 'lib_localite'=>'MPIERE – MPIERE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0267', 'lib_localite'=>'NZOKO MBIMI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0268', 'lib_localite'=>'NGAMBIO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0058', 'supprimer'=>0],
            ['code_localite'=>'LOC_0269', 'lib_localite'=>'KOMBE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0270', 'lib_localite'=>'KIBINA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0271', 'lib_localite'=>'MADIBOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0272', 'lib_localite'=>'MAFOUTA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0273', 'lib_localite'=>'MANSIMOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0274', 'lib_localite'=>'MASSISSIA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0275', 'lib_localite'=>'MAYANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0276', 'lib_localite'=>'MBOUONO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0277', 'lib_localite'=>'MOUSSOSSO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0278', 'lib_localite'=>'POTO – POTO DJOUE(SANGOLO)', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0279', 'lib_localite'=>'TSANGAMANI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0059', 'supprimer'=>0],
            ['code_localite'=>'LOC_0280', 'lib_localite'=>'IMPOH MANIANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0281', 'lib_localite'=>'ITATOLO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0282', 'lib_localite'=>'JACQUES OPANGAULT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0283', 'lib_localite'=>'MAKABANDILOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0284', 'lib_localite'=>'MIKALOU MADZOUNA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0285', 'lib_localite'=>'MATARI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0286', 'lib_localite'=>'NKOMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0060', 'supprimer'=>0],
            ['code_localite'=>'LOC_0287', 'lib_localite'=>'MWANA-NTO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0062', 'supprimer'=>0],
            ['code_localite'=>'LOC_0288', 'lib_localite'=>'DIVOUBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0062', 'supprimer'=>0],
            ['code_localite'=>'LOC_0289', 'lib_localite'=>'MARCHE CENTRAL', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0062', 'supprimer'=>0],
            ['code_localite'=>'LOC_0290', 'lib_localite'=>'MASSALA-NGOUALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0062', 'supprimer'=>0],
            ['code_localite'=>'LOC_0291', 'lib_localite'=>'KIVIDI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0062', 'supprimer'=>0],
            ['code_localite'=>'LOC_0292', 'lib_localite'=>'CAPABLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0062', 'supprimer'=>0],
            ['code_localite'=>'LOC_0293', 'lib_localite'=>'KINTOUADI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0063', 'supprimer'=>0],
            ['code_localite'=>'LOC_0294', 'lib_localite'=>'15 AOUT 1960', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0063', 'supprimer'=>0],
            ['code_localite'=>'LOC_0295', 'lib_localite'=>'MOUKOUKOULOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0063', 'supprimer'=>0],
            ['code_localite'=>'LOC_0296', 'lib_localite'=>'SOULOUKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0063', 'supprimer'=>0],
            ['code_localite'=>'LOC_0297', 'lib_localite'=>'AQUARIUM', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0063', 'supprimer'=>0],
            ['code_localite'=>'LOC_0298', 'lib_localite'=>'SANS FIL', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0299', 'lib_localite'=>'BIRANKEIM', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0300', 'lib_localite'=>'DOA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0301', 'lib_localite'=>'JUSTIE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0302', 'lib_localite'=>'MAYI POUMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0303', 'lib_localite'=>'MBOMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0304', 'lib_localite'=>'NGONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0050', 'supprimer'=>0],
            ['code_localite'=>'LOC_0305', 'lib_localite'=>'ABALA-NDOLO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0306', 'lib_localite'=>'AKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0307', 'lib_localite'=>'CENTRE-VILLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0308', 'lib_localite'=>'AKOUNOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0309', 'lib_localite'=>'MFOA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0310', 'lib_localite'=>'MPOUANGNA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0311', 'lib_localite'=>'NGAMBAO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0312', 'lib_localite'=>'NGANTSUENE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0313', 'lib_localite'=>'NGOULAYO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0314', 'lib_localite'=>'OUENZE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0315', 'lib_localite'=>'NYONFOULA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0316', 'lib_localite'=>'TALANGAI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0017', 'supprimer'=>0],
            ['code_localite'=>'LOC_0317', 'lib_localite'=>'MADIBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0318', 'lib_localite'=>'MAKOUMBOU MA MPOMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0319', 'lib_localite'=>'MASSOMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0320', 'lib_localite'=>'NTARI-NGOUARI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0321', 'lib_localite'=>'LOUBIKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0322', 'lib_localite'=>'BANZIEMO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0323', 'lib_localite'=>'VINZA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0324', 'lib_localite'=>'MBANZA-NKANDI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0325', 'lib_localite'=>'WAYAKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0326', 'lib_localite'=>'MABI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0327', 'lib_localite'=>'NGAMBARI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0328', 'lib_localite'=>'MOULOUANGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0329', 'lib_localite'=>'YALAVOUNGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0330', 'lib_localite'=>'MADIDI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0331', 'lib_localite'=>'MOUKOMBO-YALALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0018', 'supprimer'=>0],
            ['code_localite'=>'LOC_0332', 'lib_localite'=>'PAUL NGAMBI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0333', 'lib_localite'=>'NGAMBIO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0334', 'lib_localite'=>'GASTON MPOUILILOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0335', 'lib_localite'=>'NGABANOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0336', 'lib_localite'=>'LIFOULA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0337', 'lib_localite'=>'MANTENSAMA-SOUH', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0338', 'lib_localite'=>'ISSOULI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0339', 'lib_localite'=>'FLORENT TSIBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0340', 'lib_localite'=>'UNIVERSITE DENIS SASSOU NGUESSO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0341', 'lib_localite'=>'MILLE LOGEMENT', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0342', 'lib_localite'=>'IHOUEME', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0343', 'lib_localite'=>'STADE DE LA CONCORDE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0019', 'supprimer'=>0],
            ['code_localite'=>'LOC_0344', 'lib_localite'=>'MOUNGOUNGUI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0345', 'lib_localite'=>'TOLINGANA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0346', 'lib_localite'=>'BAKANDI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0347', 'lib_localite'=>'CENTRE VILLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0348', 'lib_localite'=>'ANGOLA LIBRE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0349', 'lib_localite'=>'TOSSANGANA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0350', 'lib_localite'=>'BOHONA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0351', 'lib_localite'=>'GANGANIA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0352', 'lib_localite'=>'KOMBOLA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0020', 'supprimer'=>0],
            ['code_localite'=>'LOC_0353', 'lib_localite'=>'KINDA-ODZOHO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0354', 'lib_localite'=>'YENGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0355', 'lib_localite'=>'IKOUMOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0356', 'lib_localite'=>'OHOKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0357', 'lib_localite'=>'OMBOUMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0358', 'lib_localite'=>'LINNENGUE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0359', 'lib_localite'=>'KANGUINI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0021', 'supprimer'=>0],
            ['code_localite'=>'LOC_0360', 'lib_localite'=>'OBANGUI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0022', 'supprimer'=>0],
            ['code_localite'=>'LOC_0361', 'lib_localite'=>'OYAH', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0022', 'supprimer'=>0],
            ['code_localite'=>'LOC_0362', 'lib_localite'=>'OKONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0022', 'supprimer'=>0],
            ['code_localite'=>'LOC_0363', 'lib_localite'=>'BOUTA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0364', 'lib_localite'=>'CENTRE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0365', 'lib_localite'=>'KANGAMITEMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0366', 'lib_localite'=>'OUENZE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0367', 'lib_localite'=>'EWO VILLAGE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0368', 'lib_localite'=>'EX VILLAGE KEMVANI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0369', 'lib_localite'=>'EX VILLAGE MBOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0370', 'lib_localite'=>'EX VILLAGE OKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0371', 'lib_localite'=>'EX VILLAGE OLLOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0372', 'lib_localite'=>'EX VILLAGE ONDOUNA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0023', 'supprimer'=>0],
            ['code_localite'=>'LOC_0373', 'lib_localite'=>'BACONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0374', 'lib_localite'=>'CAPABLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0375', 'lib_localite'=>'DAKAR', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0376', 'lib_localite'=>'KIMPAMBOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0377', 'lib_localite'=>'LOUBOTA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0378', 'lib_localite'=>'MANDZAOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0379', 'lib_localite'=>'MBOUKOUDOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0380', 'lib_localite'=>'MOUKOKOTADI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0381', 'lib_localite'=>'MPOUMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0382', 'lib_localite'=>'NSATOU- MEYA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0027', 'supprimer'=>0],
            ['code_localite'=>'LOC_0383', 'lib_localite'=>'PETE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0029', 'supprimer'=>0],
            ['code_localite'=>'LOC_0384', 'lib_localite'=>'STOOL', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0029', 'supprimer'=>0],
            ['code_localite'=>'LOC_0385', 'lib_localite'=>'CENTRE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0029', 'supprimer'=>0],
            ['code_localite'=>'LOC_0386', 'lib_localite'=>'MEVELLEC', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0029', 'supprimer'=>0],
            ['code_localite'=>'LOC_0387', 'lib_localite'=>'BONDZOKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0029', 'supprimer'=>0],
            ['code_localite'=>'LOC_0388', 'lib_localite'=>'LOUMINGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0389', 'lib_localite'=>'MATIBI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0390', 'lib_localite'=>'MAPINDI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0391', 'lib_localite'=>'MVOUBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0392', 'lib_localite'=>'MOUSSANDA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0393', 'lib_localite'=>'INDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0394', 'lib_localite'=>'MALIMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0395', 'lib_localite'=>'MOUSSIEHOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0396', 'lib_localite'=>'MIKAMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0397', 'lib_localite'=>'LOSSO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0398', 'lib_localite'=>'MOUKANDA ', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0399', 'lib_localite'=>'MONGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0007', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0015', 'supprimer'=>0],
            ['code_localite'=>'LOC_0400', 'lib_localite'=>'ILE MBAMOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0001', 'supprimer'=>0],
            ['code_localite'=>'LOC_0401', 'lib_localite'=>'TCHAMBA NZASSI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0002', 'supprimer'=>0],
            ['code_localite'=>'LOC_0402', 'lib_localite'=>'BETOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0403', 'lib_localite'=>'BOUANELA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0404', 'lib_localite'=>'DONGOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0405', 'lib_localite'=>'ENYELLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0406', 'lib_localite'=>'EPENA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0407', 'lib_localite'=>'IMPFONDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0408', 'lib_localite'=>'LIRANGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0003', 'supprimer'=>0],
            ['code_localite'=>'LOC_0409', 'lib_localite'=>'KABO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0410', 'lib_localite'=>'MOKEKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0411', 'lib_localite'=>'NGBALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0412', 'lib_localite'=>'PIKOUNDA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0413', 'lib_localite'=>'SEMBE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0414', 'lib_localite'=>'SOUANKE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0004', 'supprimer'=>0],
            ['code_localite'=>'LOC_0415', 'lib_localite'=>'ETOUMBI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0416', 'lib_localite'=>'EWO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0417', 'lib_localite'=>'KELLE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0418', 'lib_localite'=>'MBAMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0419', 'lib_localite'=>'MBOMO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0420', 'lib_localite'=>'OKOYO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0005', 'supprimer'=>0],
            ['code_localite'=>'LOC_0421', 'lib_localite'=>'OWANDO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0422', 'lib_localite'=>'OYO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0423', 'lib_localite'=>'MAKOUA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0424', 'lib_localite'=>'TCHICAPIKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0425', 'lib_localite'=>'NGOKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0426', 'lib_localite'=>'NTOKOU', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0427', 'lib_localite'=>'MOSSAKA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0428', 'lib_localite'=>'LOUKOLELA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0429', 'lib_localite'=>'BOUNDJI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0430', 'lib_localite'=>'BOKOMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0006', 'supprimer'=>0],
            ['code_localite'=>'LOC_0431', 'lib_localite'=>'ABALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0432', 'lib_localite'=>'ALLEMBE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0433', 'lib_localite'=>'DJAMBALA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0434', 'lib_localite'=>'GAMBOMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0435', 'lib_localite'=>'NGO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0436', 'lib_localite'=>'LEKANA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0437', 'lib_localite'=>'OLLOMBO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0438', 'lib_localite'=>'MAKOTIMPOKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0439', 'lib_localite'=>'ONGOGNI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0440', 'lib_localite'=>'MBON', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0441', 'lib_localite'=>'MPOUYA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0007', 'supprimer'=>0],
            ['code_localite'=>'LOC_0442', 'lib_localite'=>'LOUINGUI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0443', 'lib_localite'=>'LOUMO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0444', 'lib_localite'=>'IGNE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0445', 'lib_localite'=>'MAYAMA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0446', 'lib_localite'=>'VINDZA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0447', 'lib_localite'=>'MBANZA-NDOUNGA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0448', 'lib_localite'=>'KIMBA', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0449', 'lib_localite'=>'NGABE', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0450', 'lib_localite'=>'MINDOULI', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
            ['code_localite'=>'LOC_0451', 'lib_localite'=>'BOKO', 'code_officel'=>NULL, 'code_type_localite'=>'TPLOC_0002', 'pompes_funebres'=>0, 'code_localite_parent'=>'LOC_0008', 'supprimer'=>0],
        ];

        foreach ($data as $d){
            Localite::create($d);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        $this->command->info('✅ ' . count($data) . ' localités insérées avec succès');
        $this->command->info('📍 Codes postaux conformes au Chapitre 3, Article 11 du Décret portant codification postale en République _250914_170727');
    }
}
