<?php

declare(strict_types=1);

namespace PkiSdk;

/**
 * SDK-first signer and institution lifecycle client.
 *
 * Covers /v1/signers (signer create/list/get/status/revoke/renew)
 * and /v1/institutions (institution create/list/get).
 *
 * Historical enrollment methods remain available on SignatureClient for
 * read-only backward compatibility.
 */
class SignerClient
{
    private const TIMEOUT_READ = 3;
    private const TIMEOUT_WRITE = 90;

    public function __construct(
        private readonly TrustClientInterface $client,
    ) {}

    /**
     * @param array<string, mixed> $input
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function create(array $input, ?string $idempotencyKey = null): array
    {
        if ($idempotencyKey !== null && ! isset($input['idempotency_key'])) {
            $input['idempotency_key'] = $idempotencyKey;
        }

        return $this->client->post('/v1/signers', $input, self::TIMEOUT_WRITE);
    }

    /**
     * @param array<int, array<string, mixed>> $items
     * @param array<string, mixed>             $options
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function createBatch(array $items, array $options = []): array
    {
        return $this->client->post(
            '/v1/signers/batch',
            array_merge($options, ['items' => $items]),
            self::TIMEOUT_WRITE
        );
    }

    /**
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function getBatch(string $batchId): array
    {
        return $this->client->get('/v1/signers/batch/' . rawurlencode($batchId), self::TIMEOUT_READ);
    }

    /**
     * Create a short-lived browser token enrollment session for hardware-token flows.
     *
     * @param array<string, mixed> $input
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function createTokenEnrollmentSession(array $input): array
    {
        return $this->client->post('/v1/token-enrollment-sessions', $input, self::TIMEOUT_WRITE);
    }

    /**
     * Submit the CSR generated by the browser/token flow.
     *
     * This call is intentionally public-token based: the browser sends only the
     * short-lived session token, never the tenant API key.
     *
     * @param array<string, mixed> $input
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function completeTokenEnrollment(array $input): array
    {
        return $this->client->post('/v1/token-enrollments', $input, self::TIMEOUT_WRITE);
    }

    /**
     * @param array<string, scalar|null> $filters
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function list(array $filters = []): array
    {
        $query = array_filter(
            $filters,
            static fn (mixed $value): bool => $value !== null && $value !== ''
        );
        $path = '/v1/signers';
        if ($query !== []) {
            $path .= '?' . http_build_query($query);
        }

        return $this->client->get($path, self::TIMEOUT_READ);
    }

    /**
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function get(string $actorId): array
    {
        return $this->client->get('/v1/signers/' . rawurlencode($actorId), self::TIMEOUT_READ);
    }

    /**
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function status(string $actorId): array
    {
        return $this->client->get('/v1/signers/' . rawurlencode($actorId) . '/status', self::TIMEOUT_READ);
    }

    /**
     * Find a signer by certificate serial number (case-insensitive).
     * Used for certificate-based authentication flows.
     *
     * @return array{signer: array<string, mixed>}
     * @throws TrustException
     */
    public function lookupBySerial(string $serialHex): array
    {
        return $this->client->get('/v1/signers/lookup?serial_number=' . rawurlencode($serialHex), self::TIMEOUT_READ);
    }

    /**
     * Aggregate signer counts by status, tenant-scoped.
     *
     * @return array{stats: array<string, int|string>}
     * @throws TrustException
     */
    public function stats(): array
    {
        return $this->client->get('/v1/signers/stats', self::TIMEOUT_READ);
    }

    /**
     * @param array<string, mixed> $options
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function revoke(string $actorId, string $reason = 'unspecified', array $options = []): array
    {
        return $this->client->post(
            '/v1/signers/' . rawurlencode($actorId) . '/revoke',
            array_merge($options, ['reason' => $reason]),
            self::TIMEOUT_WRITE
        );
    }

    /**
     * @param array<string, mixed> $options
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function suspend(string $actorId, array $options = []): array
    {
        return $this->client->post(
            '/v1/signers/' . rawurlencode($actorId) . '/suspend',
            $options,
            self::TIMEOUT_WRITE
        );
    }

    /**
     * Renew a signer certificate while keeping actor_id stable.
     *
     * @param array<string, mixed> $options
     * @return array<string, mixed>
     * @throws TrustException
     */
    public function renew(string $actorId, array $options = []): array
    {
        return $this->client->post(
            '/v1/signers/' . rawurlencode($actorId) . '/renew',
            $options,
            self::TIMEOUT_WRITE
        );
    }

    /**
     * Decrypt the escrowed private key of a signer enrolled with
     * enrollment_type=p12 and return a brand-new PKCS#12 bundle + passphrase.
     * Repeatable: a forgotten PIN is resolved by calling this again, not by
     * revoking the signer.
     *
     * @param array<string, mixed> $options
     * @return array{actor_id: string, passphrase: string, p12_base64: string, serial_number: string|null}
     * @throws TrustException
     */
    public function escrowP12(string $actorId, array $options = []): array
    {
        return $this->client->post(
            '/v1/signers/' . rawurlencode($actorId) . '/escrow-p12',
            $options,
            self::TIMEOUT_WRITE
        );
    }

    // ── Institution SDK-first lifecycle (/v1/institutions) ───────────────────

    /**
     * Enroll a new institution via the SDK-first /v1/institutions endpoint.
     *
     * Creates a Transit key + CSR + X.509 cert in OpenBao and persists the
     * institution record. Returns the full institution payload including
     * signing_key_name, cert_pem, issuer_dn, not_before, etc.
     *
     * @param  array<string, mixed> $input  Must include institution_id and nom.
     *                                      Accepts common_name, organization, ou.
     * @return array{institution: array<string, mixed>}
     * @throws TrustException
     */
    public function createInstitution(array $input): array
    {
        return $this->client->post('/v1/institutions', $input, self::TIMEOUT_WRITE);
    }

    /**
     * List all institutions.
     *
     * @return array{institutions: list<array<string, mixed>>}
     * @throws TrustException
     */
    public function listInstitutions(): array
    {
        return $this->client->get('/v1/institutions', self::TIMEOUT_READ);
    }

    /**
     * Retrieve a single institution by institution_id.
     *
     * @return array{institution: array<string, mixed>}
     * @throws TrustException
     */
    public function getInstitution(string $institutionId): array
    {
        return $this->client->get('/v1/institutions/' . rawurlencode($institutionId), self::TIMEOUT_READ);
    }
}
